name: example

on: push

jobs:
  build: # имя взято для примера
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v4
      # Устанавливаем Node.js
      # Ставим зависимости
      - run: make install
      # Запускаем линтер
      - run: make lint
      - name: run tests
        run: make test # name и run относятся к одной задаче, поэтому дефис ставится только перед name